/**
 * Obsidian Brain — the project's persistent knowledge layer.
 *
 * Each department writes to its section after runs. A nightly consolidator
 * compresses the day's learnings into a digest. A morning briefing reads
 * the vault and primes all agents with relevant context.
 *
 * Structure:
 *   ~/Obsidian/Nexorra/
 *     Daily/           — Daily digests (one per day)
 *     Leads/           — Per-lead notes (synced from DB)
 *     Clients/         — Per-client profiles
 *     Research/         — Market research, competitor analysis
 *     Engineering/      — ADRs, bug reports, architecture decisions
 *     Marketing/        — Campaign results, copy performance, outreach patterns
 *     Experiments/      — A/B test results, hypothesis outcomes
 *     Briefings/        — Morning briefing summaries (read by all agents)
 *     Index.md          — Master index with links to everything
 */

import fs from 'fs/promises';
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import path from 'path';
import os from 'os';

const VAULT = path.join(os.homedir(), 'Obsidian', 'Nexorra');

const SECTIONS = [
  'Daily', 'Leads', 'Clients', 'Research', 'Engineering',
  'Marketing', 'Experiments', 'Briefings',
] as const;

type Section = typeof SECTIONS[number];

function ensureDir(dir: string) {
  mkdirSync(dir, { recursive: true });
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function now(): string {
  return new Date().toISOString().slice(0, 19).replace('T', ' ');
}

// ─── Writing ──────────────────────────────────────────────────────────────────

/**
 * Append content to a section note. Creates the file if it doesn't exist.
 * Used by agents to log findings, decisions, results after each run.
 */
export function appendToSection(
  section: Section,
  filename: string,
  content: string,
  heading?: string
): void {
  ensureDir(path.join(VAULT, section));
  const filepath = path.join(VAULT, section, filename.endsWith('.md') ? filename : `${filename}.md`);

  const timestamp = now();
  const block = heading
    ? `\n## ${heading} (${timestamp})\n\n${content}\n`
    : `\n### ${timestamp}\n\n${content}\n`;

  if (existsSync(filepath)) {
    const existing = readFileSync(filepath, 'utf-8');
    writeFileSync(filepath, existing + block, 'utf-8');
  } else {
    writeFileSync(filepath, `# ${filename.replace('.md', '')}\n${block}`, 'utf-8');
  }
}

/**
 * Write a complete section note (overwrites).
 */
export function writeSection(section: Section, filename: string, content: string): void {
  ensureDir(path.join(VAULT, section));
  const filepath = path.join(VAULT, section, filename.endsWith('.md') ? filename : `${filename}.md`);
  writeFileSync(filepath, content, 'utf-8');
}

/**
 * Department-specific writers — called by agents after their runs.
 */
export const writers = {
  /** Glen writes daily report */
  dailyReport(stats: {
    leadsScraped: number;
    leadsResearched: number;
    emailsSent: number;
    emailReplies: number;
    igDmsSent: number;
    igReplies: number;
    clientReplies: number;
    bookings: number;
    agentRuns: number;
    totalTokens: number;
    costUsd: number;
  }): void {
    const date = today();
    const content = `# Daily Report — ${date}

## Metrics
| Metric | Count |
|--------|-------|
| Leads scraped | ${stats.leadsScraped} |
| Leads researched | ${stats.leadsResearched} |
| Cold emails sent | ${stats.emailsSent} |
| Email replies | ${stats.emailReplies} |
| IG DMs sent | ${stats.igDmsSent} |
| IG replies | ${stats.igReplies} |
| Client replies | ${stats.clientReplies} |
| Bookings | ${stats.bookings} |
| Agent runs | ${stats.agentRuns} |
| Total tokens | ${stats.totalTokens.toLocaleString()} |
| Cost | $${stats.costUsd.toFixed(2)} |

## Notes
*(Auto-generated by Glen at ${now()})*
`;
    writeSection('Daily', `${date}.md`, content);
  },

  /** Jeff/Derek write research findings */
  research(topic: string, findings: string, agent: string): void {
    appendToSection('Research', topic, `**${agent}**: ${findings}`);
  },

  /** Stacey/Vera write marketing insights */
  marketing(topic: string, content: string, agent: string): void {
    appendToSection('Marketing', topic, `**${agent}**: ${content}`);
  },

  /** Barny/team write engineering decisions */
  engineering(topic: string, content: string, agent: string): void {
    appendToSection('Engineering', topic, `**${agent}**: ${content}`);
  },

  /** Hugo/Mira write experiment results */
  experiment(name: string, result: string, agent: string): void {
    appendToSection('Experiments', `${today()}-experiments`, `**${name}** (${agent}): ${result}`);
  },

  /** Iris writes client profiles */
  clientProfile(clientName: string, content: string): void {
    writeSection('Clients', clientName, content);
  },
};

// ─── Reading ──────────────────────────────────────────────────────────────────

/**
 * Read a specific note from any section.
 */
export function readNote(section: Section, filename: string): string | null {
  const filepath = path.join(VAULT, section, filename.endsWith('.md') ? filename : `${filename}.md`);
  if (!existsSync(filepath)) return null;
  return readFileSync(filepath, 'utf-8');
}

/**
 * List all notes in a section.
 */
export function listNotes(section: Section): string[] {
  const dir = path.join(VAULT, section);
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter(f => f.endsWith('.md')).sort();
}

/**
 * Read the most recent daily report.
 */
export function latestDaily(): string | null {
  const notes = listNotes('Daily');
  if (notes.length === 0) return null;
  return readNote('Daily', notes[notes.length - 1]);
}

/**
 * Read the most recent morning briefing.
 */
export function latestBriefing(): string | null {
  const notes = listNotes('Briefings');
  if (notes.length === 0) return null;
  return readNote('Briefings', notes[notes.length - 1]);
}

// ─── Nightly Consolidator ─────────────────────────────────────────────────────

/**
 * Called at ~1 AM (before sleep). Reads today's scattered notes across all
 * sections and writes a consolidated digest to Daily/{date}-digest.md.
 * This is what the morning briefing reads.
 */
export function consolidateDay(): string {
  const date = today();
  const parts: string[] = [`# Nexorra Digest — ${date}\n`];

  // Daily report
  const daily = readNote('Daily', date);
  if (daily) parts.push(`## Daily Metrics\n${daily.replace(/^# .+\n/, '')}\n`);

  // Research activity
  const researchNotes = listNotes('Research');
  const todayResearch = researchNotes.filter(n => {
    const content = readNote('Research', n) || '';
    return content.includes(date);
  });
  if (todayResearch.length > 0) {
    parts.push(`## Research (${todayResearch.length} topics)\n`);
    for (const note of todayResearch.slice(0, 5)) {
      const content = readNote('Research', note) || '';
      const lines = content.split('\n').filter(l => l.includes(date)).slice(0, 3);
      parts.push(`### ${note.replace('.md', '')}\n${lines.join('\n')}\n`);
    }
  }

  // Marketing activity
  const marketingNotes = listNotes('Marketing');
  const todayMarketing = marketingNotes.filter(n => {
    const content = readNote('Marketing', n) || '';
    return content.includes(date);
  });
  if (todayMarketing.length > 0) {
    parts.push(`## Marketing (${todayMarketing.length} topics)\n`);
    for (const note of todayMarketing.slice(0, 3)) {
      const content = readNote('Marketing', note) || '';
      const recent = content.split('\n').filter(l => l.includes(date)).slice(0, 2);
      parts.push(`- **${note.replace('.md', '')}**: ${recent.join(' ')}\n`);
    }
  }

  // Engineering decisions
  const engNotes = listNotes('Engineering');
  const todayEng = engNotes.filter(n => {
    const content = readNote('Engineering', n) || '';
    return content.includes(date);
  });
  if (todayEng.length > 0) {
    parts.push(`## Engineering (${todayEng.length} items)\n`);
    for (const note of todayEng.slice(0, 3)) {
      parts.push(`- ${note.replace('.md', '')}\n`);
    }
  }

  // Experiments
  const expContent = readNote('Experiments', `${date}-experiments`);
  if (expContent) {
    parts.push(`## Experiments\n${expContent.replace(/^# .+\n/, '')}\n`);
  }

  // Lead stats
  const leadCount = listNotes('Leads').length;
  const clientCount = listNotes('Clients').length;
  parts.push(`## Vault Stats\n- ${leadCount} lead notes\n- ${clientCount} client profiles\n`);

  const digest = parts.join('\n');
  writeSection('Daily', `${date}-digest.md`, digest);
  return digest;
}

// ─── Morning Briefing ─────────────────────────────────────────────────────────

/**
 * Called at ~10 AM (after wake). Reads the latest digest and creates a
 * concise briefing that gets injected into every agent's context for the day.
 * This replaces stale primers with fresh vault knowledge.
 */
export function generateMorningBriefing(): string {
  const date = today();

  // Read yesterday's digest (consolidated at 1 AM)
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
  const digest = readNote('Daily', `${yesterday}-digest`) || readNote('Daily', `${date}-digest`);

  // Read latest experiment results
  const expNotes = listNotes('Experiments');
  const latestExp = expNotes.length > 0 ? readNote('Experiments', expNotes[expNotes.length - 1]) : null;

  // Count vault stats
  const leadCount = listNotes('Leads').length;
  const clientCount = listNotes('Clients').length;
  const researchCount = listNotes('Research').length;

  const briefing = `# Morning Briefing — ${date}

## Vault: ${leadCount} leads, ${clientCount} clients, ${researchCount} research topics

${digest ? `## Yesterday's Digest\n${digest.split('\n').slice(0, 30).join('\n')}\n` : '## No digest from yesterday.\n'}
${latestExp ? `## Latest Experiments\n${latestExp.split('\n').slice(0, 10).join('\n')}\n` : ''}
## Active Context
- All agents have access to ~/Obsidian/Nexorra/ via filesystem MCP
- Write findings to the vault using brain.writers.{department}()
- Read from vault to avoid re-querying DB for known information

*(Generated at ${now()})*
`;

  writeSection('Briefings', `${date}.md`, briefing);
  return briefing;
}

// ─── Index ────────────────────────────────────────────────────────────────────

/**
 * Rebuild the master index. Links to all sections and recent notes.
 */
export function rebuildIndex(): void {
  const parts: string[] = [`# Nexorra Knowledge Vault\n\n*Last updated: ${now()}*\n`];

  for (const section of SECTIONS) {
    const notes = listNotes(section);
    parts.push(`\n## ${section} (${notes.length} notes)\n`);
    for (const note of notes.slice(-10)) {
      parts.push(`- [[${section}/${note.replace('.md', '')}]]`);
    }
  }

  writeFileSync(path.join(VAULT, 'Index.md'), parts.join('\n'), 'utf-8');
}

export default {
  appendToSection, writeSection, readNote, listNotes,
  latestDaily, latestBriefing,
  consolidateDay, generateMorningBriefing, rebuildIndex,
  writers,
};
