-- 540+ contacts for agency account
-- Includes 117 subaccount-named contacts + 423+ generic leads
-- Run in Supabase SQL editor

DO $$
DECLARE
  v_account_id uuid := 'da99b768-79dd-48f8-af86-abf95e61a69f';
BEGIN

-- BATCH 1: 117 named contacts (subaccount names + realistic real estate brokerages)
INSERT INTO contacts (account_id, first_name, last_name, email, phone, company, status, source, created_at, updated_at)
VALUES
(v_account_id,'Jordan','Whitfield','jordan.whitfield@remax.com','+14155550101','RE/MAX Premier','customer','cold_email',now()-interval '14 months',now()-interval '2 months'),
(v_account_id,'Aisha','Johnson','aisha.johnson@kwrealty.com','+14155550102','Keller Williams','customer','cold_email',now()-interval '13 months',now()-interval '1 month'),
(v_account_id,'Michael','O''Connor','michael.oconnor@coldwellbanker.com','+14155550103','Coldwell Banker','customer','referral',now()-interval '13 months',now()-interval '3 months'),
(v_account_id,'Sarah','Chen','sarah.chen@compass.com','+14155550104','Compass Realty','customer','instagram',now()-interval '12 months',now()-interval '2 months'),
(v_account_id,'Robert','Davis','robert.davis@sothebys.com','+14155550105','Sotheby''s Realty','customer','cold_email',now()-interval '12 months',now()-interval '1 month'),
(v_account_id,'Emma','Wilson','emma.wilson@bhhs.com','+14155550106','Berkshire Hathaway','customer','cold_email',now()-interval '11 months',now()-interval '2 months'),
(v_account_id,'Carlos','Martinez','carlos.martinez@century21.com','+14155550107','Century 21','customer','referral',now()-interval '11 months',now()-interval '1 month'),
(v_account_id,'Jennifer','Lee','jennifer.lee@exp.com','+14155550108','eXp Realty','customer','instagram',now()-interval '10 months',now()-interval '3 months'),
(v_account_id,'David','Thompson','david.thompson@redfin.com','+14155550109','Redfin','customer','cold_email',now()-interval '10 months',now()-interval '2 months'),
(v_account_id,'Lisa','Anderson','lisa.anderson@kwrealty.com','+14155550110','Keller Williams','customer','cold_email',now()-interval '10 months',now()-interval '1 month'),
(v_account_id,'James','Garcia','james.garcia@remax.com','+14155550111','RE/MAX','customer','referral',now()-interval '9 months',now()-interval '2 months'),
(v_account_id,'Patricia','Miller','patricia.miller@compass.com','+14155550112','Compass','customer','cold_email',now()-interval '9 months',now()-interval '1 month'),
(v_account_id,'Daniel','Taylor','daniel.taylor@bhhs.com','+14155550113','Berkshire Hathaway','customer','instagram',now()-interval '9 months',now()-interval '2 months'),
(v_account_id,'Mary','Jackson','mary.jackson@coldwellbanker.com','+14155550114','Coldwell Banker','customer','cold_email',now()-interval '8 months',now()-interval '3 months'),
(v_account_id,'Christopher','Harris','christopher.harris@sothebys.com','+14155550115','Sotheby''s Realty','customer','referral',now()-interval '8 months',now()-interval '1 month'),
(v_account_id,'Barbara','White','barbara.white@century21.com','+14155550116','Century 21','customer','cold_email',now()-interval '8 months',now()-interval '2 months'),
(v_account_id,'Matthew','Martin','matthew.martin@exp.com','+14155550117','eXp Realty','customer','cold_email',now()-interval '7 months',now()-interval '1 month'),
(v_account_id,'Susan','Clark','susan.clark@remax.com','+14155550118','RE/MAX','customer','instagram',now()-interval '7 months',now()-interval '2 months'),
(v_account_id,'Anthony','Robinson','anthony.robinson@kwrealty.com','+14155550119','Keller Williams','customer','cold_email',now()-interval '7 months',now()-interval '1 month'),
(v_account_id,'Jessica','Lewis','jessica.lewis@compass.com','+14155550120','Compass','customer','referral',now()-interval '6 months',now()-interval '2 months'),
(v_account_id,'Andrew','Walker','andrew.walker@bhhs.com','+14155550121','Berkshire Hathaway','customer','cold_email',now()-interval '6 months',now()-interval '1 month'),
(v_account_id,'Karen','Hall','karen.hall@coldwellbanker.com','+14155550122','Coldwell Banker','customer','cold_email',now()-interval '6 months',now()-interval '2 months'),
(v_account_id,'Ryan','Young','ryan.young@sothebys.com','+14155550123','Sotheby''s Realty','customer','instagram',now()-interval '5 months',now()-interval '1 month'),
(v_account_id,'Betty','Allen','betty.allen@century21.com','+14155550124','Century 21','customer','referral',now()-interval '5 months',now()-interval '2 months'),
(v_account_id,'Joshua','King','joshua.king@exp.com','+14155550125','eXp Realty','customer','cold_email',now()-interval '5 months',now()-interval '1 month'),
(v_account_id,'Dorothy','Wright','dorothy.wright@remax.com','+14155550126','RE/MAX','customer','cold_email',now()-interval '5 months',now()-interval '2 months'),
(v_account_id,'Brandon','Scott','brandon.scott@kwrealty.com','+14155550127','Keller Williams','customer','instagram',now()-interval '4 months',now()-interval '1 month'),
(v_account_id,'Sandra','Torres','sandra.torres@compass.com','+14155550128','Compass','customer','cold_email',now()-interval '4 months',now()-interval '1 month'),
(v_account_id,'Samuel','Green','samuel.green@bhhs.com','+14155550129','Berkshire Hathaway','customer','referral',now()-interval '4 months',now()-interval '1 month'),
(v_account_id,'Margaret','Adams','margaret.adams@coldwellbanker.com','+14155550130','Coldwell Banker','customer','cold_email',now()-interval '4 months',now()-interval '2 months'),
(v_account_id,'Tyler','Baker','tyler.baker@sothebys.com','+14155550131','Sotheby''s Realty','customer','cold_email',now()-interval '3 months',now()-interval '1 month'),
(v_account_id,'Helen','Nelson','helen.nelson@century21.com','+14155550132','Century 21','customer','instagram',now()-interval '3 months',now()-interval '1 month'),
(v_account_id,'Sean','Hill','sean.hill@exp.com','+14155550133','eXp Realty','customer','referral',now()-interval '3 months',now()-interval '1 month'),
(v_account_id,'Donna','Carter','donna.carter@remax.com','+14155550134','RE/MAX','customer','cold_email',now()-interval '3 months',now()-interval '2 months'),
(v_account_id,'Austin','Mitchell','austin.mitchell@kwrealty.com','+14155550135','Keller Williams','customer','cold_email',now()-interval '3 months',now()-interval '1 month'),
(v_account_id,'Carol','Perez','carol.perez@compass.com','+14155550136','Compass','customer','cold_email',now()-interval '2 months',now()-interval '1 month'),
(v_account_id,'Justin','Roberts','justin.roberts@bhhs.com','+14155550137','Berkshire Hathaway','customer','instagram',now()-interval '2 months',now()-interval '1 month'),
(v_account_id,'Ruth','Turner','ruth.turner@coldwellbanker.com','+14155550138','Coldwell Banker','customer','referral',now()-interval '2 months',now()-interval '1 month'),
(v_account_id,'Jonathan','Phillips','jonathan.phillips@sothebys.com','+14155550139','Sotheby''s Realty','customer','cold_email',now()-interval '2 months',now()-interval '2 weeks'),
(v_account_id,'Sharon','Campbell','sharon.campbell@century21.com','+14155550140','Century 21','customer','cold_email',now()-interval '2 months',now()-interval '2 weeks'),
(v_account_id,'Benjamin','Parker','benjamin.parker@exp.com','+14155550141','eXp Realty','customer','cold_email',now()-interval '2 months',now()-interval '2 weeks'),
(v_account_id,'Michelle','Evans','michelle.evans@remax.com','+14155550142','RE/MAX','customer','instagram',now()-interval '6 weeks',now()-interval '2 weeks'),
(v_account_id,'Nicholas','Edwards','nicholas.edwards@kwrealty.com','+14155550143','Keller Williams','customer','referral',now()-interval '6 weeks',now()-interval '2 weeks'),
(v_account_id,'Emily','Collins','emily.collins@compass.com','+14155550144','Compass','customer','cold_email',now()-interval '5 weeks',now()-interval '1 week'),
(v_account_id,'Eric','Stewart','eric.stewart@bhhs.com','+14155550145','Berkshire Hathaway','customer','cold_email',now()-interval '5 weeks',now()-interval '1 week'),
(v_account_id,'Deborah','Sanchez','deborah.sanchez@coldwellbanker.com','+14155550146','Coldwell Banker','customer','cold_email',now()-interval '4 weeks',now()-interval '1 week'),
(v_account_id,'Stephen','Morris','stephen.morris@sothebys.com','+14155550147','Sotheby''s Realty','customer','instagram',now()-interval '4 weeks',now()-interval '1 week'),
(v_account_id,'Pamela','Rogers','pamela.rogers@century21.com','+14155550148','Century 21','customer','referral',now()-interval '4 weeks',now()-interval '1 week'),
(v_account_id,'Patrick','Reed','patrick.reed@exp.com','+14155550149','eXp Realty','customer','cold_email',now()-interval '3 weeks',now()-interval '1 week'),
(v_account_id,'Carolyn','Cook','carolyn.cook@remax.com','+14155550150','RE/MAX','customer','cold_email',now()-interval '3 weeks',now()-interval '1 week'),
(v_account_id,'Kyle','Bailey','kyle.bailey@kwrealty.com','+14155550151','Keller Williams','customer','cold_email',now()-interval '3 weeks',now()-interval '1 week'),
(v_account_id,'Virginia','Bell','virginia.bell@compass.com','+14155550152','Compass','customer','instagram',now()-interval '2 weeks',now()-interval '5 days'),
(v_account_id,'Gary','Cooper','gary.cooper@bhhs.com','+14155550153','Berkshire Hathaway','customer','referral',now()-interval '2 weeks',now()-interval '5 days'),
(v_account_id,'Judith','Murphy','judith.murphy@coldwellbanker.com','+14155550154','Coldwell Banker','customer','cold_email',now()-interval '2 weeks',now()-interval '5 days'),
(v_account_id,'Edward','Richardson','edward.richardson@sothebys.com','+14155550155','Sotheby''s Realty','customer','cold_email',now()-interval '2 weeks',now()-interval '5 days'),
(v_account_id,'Julia','Cox','julia.cox@century21.com','+14155550156','Century 21','customer','cold_email',now()-interval '2 weeks',now()-interval '4 days'),
(v_account_id,'Jerry','Howard','jerry.howard@exp.com','+14155550157','eXp Realty','customer','instagram',now()-interval '10 days',now()-interval '4 days'),
(v_account_id,'Evelyn','Ward','evelyn.ward@remax.com','+14155550158','RE/MAX','customer','referral',now()-interval '10 days',now()-interval '4 days'),
(v_account_id,'Keith','Torres','keith.torres@kwrealty.com','+14155550159','Keller Williams','customer','cold_email',now()-interval '9 days',now()-interval '3 days'),
(v_account_id,'Christine','Peterson','christine.peterson@compass.com','+14155550160','Compass','customer','cold_email',now()-interval '8 days',now()-interval '3 days'),
(v_account_id,'Terry','Gray','terry.gray@bhhs.com','+14155550161','Berkshire Hathaway','customer','cold_email',now()-interval '7 days',now()-interval '2 days'),
(v_account_id,'Katherine','Ramirez','katherine.ramirez@coldwellbanker.com','+14155550162','Coldwell Banker','customer','instagram',now()-interval '7 days',now()-interval '2 days'),
(v_account_id,'Gerald','James','gerald.james@sothebys.com','+14155550163','Sotheby''s Realty','customer','referral',now()-interval '6 days',now()-interval '2 days'),
(v_account_id,'Janet','Watson','janet.watson@century21.com','+14155550164','Century 21','customer','cold_email',now()-interval '6 days',now()-interval '2 days'),
(v_account_id,'Scott','Brooks','scott.brooks@exp.com','+14155550165','eXp Realty','customer','cold_email',now()-interval '5 days',now()-interval '1 day'),
(v_account_id,'Maria','Kelly','maria.kelly@remax.com','+14155550166','RE/MAX','customer','cold_email',now()-interval '5 days',now()-interval '1 day'),
(v_account_id,'Roger','Price','roger.price@kwrealty.com','+14155550167','Keller Williams','customer','instagram',now()-interval '4 days',now()-interval '1 day'),
(v_account_id,'Alice','Bennett','alice.bennett@compass.com','+14155550168','Compass','customer','referral',now()-interval '4 days',now()-interval '1 day'),
(v_account_id,'Johnny','Wood','johnny.wood@bhhs.com','+14155550169','Berkshire Hathaway','customer','cold_email',now()-interval '3 days',now()),
(v_account_id,'Jean','Barnes','jean.barnes@coldwellbanker.com','+14155550170','Coldwell Banker','customer','cold_email',now()-interval '3 days',now()),
(v_account_id,'Jose','Ross','jose.ross@sothebys.com','+14155550171','Sotheby''s Realty','customer','cold_email',now()-interval '2 days',now()),
(v_account_id,'Diana','Henderson','diana.henderson@century21.com','+14155550172','Century 21','customer','instagram',now()-interval '2 days',now()),
(v_account_id,'Earl','Coleman','earl.coleman@exp.com','+14155550173','eXp Realty','customer','referral',now()-interval '2 days',now()),
(v_account_id,'Frances','Jenkins','frances.jenkins@remax.com','+14155550174','RE/MAX','customer','cold_email',now()-interval '2 days',now()),
(v_account_id,'Henry','Perry','henry.perry@kwrealty.com','+14155550175','Keller Williams','customer','cold_email',now()-interval '1 day',now()),
(v_account_id,'Lois','Powell','lois.powell@compass.com','+14155550176','Compass','customer','cold_email',now()-interval '1 day',now()),
(v_account_id,'Walter','Long','walter.long@bhhs.com','+14155550177','Berkshire Hathaway','customer','instagram',now()-interval '1 day',now()),
(v_account_id,'Martha','Patterson','martha.patterson@coldwellbanker.com','+14155550178','Coldwell Banker','customer','referral',now()-interval '20 hours',now()),
(v_account_id,'Arthur','Hughes','arthur.hughes@sothebys.com','+14155550179','Sotheby''s Realty','customer','cold_email',now()-interval '18 hours',now()),
(v_account_id,'Tammy','Flores','tammy.flores@century21.com','+14155550180','Century 21','customer','cold_email',now()-interval '16 hours',now()),
(v_account_id,'Philip','Washington','philip.washington@exp.com','+14155550181','eXp Realty','customer','cold_email',now()-interval '14 hours',now()),
(v_account_id,'Janice','Butler','janice.butler@remax.com','+14155550182','RE/MAX','customer','instagram',now()-interval '12 hours',now()),
(v_account_id,'Randy','Simmons','randy.simmons@kwrealty.com','+14155550183','Keller Williams','customer','referral',now()-interval '10 hours',now()),
(v_account_id,'Denise','Foster','denise.foster@compass.com','+14155550184','Compass','customer','cold_email',now()-interval '8 hours',now()),
(v_account_id,'Roy','Gonzales','roy.gonzales@bhhs.com','+14155550185','Berkshire Hathaway','customer','cold_email',now()-interval '7 hours',now()),
(v_account_id,'Shirley','Bryant','shirley.bryant@coldwellbanker.com','+14155550186','Coldwell Banker','customer','cold_email',now()-interval '6 hours',now()),
(v_account_id,'Joe','Alexander','joe.alexander@sothebys.com','+14155550187','Sotheby''s Realty','customer','instagram',now()-interval '5 hours',now()),
(v_account_id,'Wanda','Russell','wanda.russell@century21.com','+14155550188','Century 21','customer','referral',now()-interval '4 hours',now()),
(v_account_id,'Louis','Griffin','louis.griffin@exp.com','+14155550189','eXp Realty','customer','cold_email',now()-interval '3 hours',now()),
(v_account_id,'Brenda','Diaz','brenda.diaz@remax.com','+14155550190','RE/MAX','customer','cold_email',now()-interval '2 hours',now()),
(v_account_id,'Harold','Graham','harold.graham@kwrealty.com','+14155550191','Keller Williams','customer','cold_email',now()-interval '90 minutes',now()),
(v_account_id,'Judith','Sullivan','judith.sullivan@compass.com','+14155550192','Compass','customer','instagram',now()-interval '80 minutes',now()),
(v_account_id,'Frederick','Wallace','frederick.wallace@bhhs.com','+14155550193','Berkshire Hathaway','customer','referral',now()-interval '70 minutes',now()),
(v_account_id,'Bonnie','West','bonnie.west@coldwellbanker.com','+14155550194','Coldwell Banker','customer','cold_email',now()-interval '60 minutes',now()),
(v_account_id,'Raymond','Cole','raymond.cole@sothebys.com','+14155550195','Sotheby''s Realty','customer','cold_email',now()-interval '50 minutes',now()),
(v_account_id,'Gloria','Jordan','gloria.jordan@century21.com','+14155550196','Century 21','customer','cold_email',now()-interval '40 minutes',now()),
(v_account_id,'Carl','Owens','carl.owens@exp.com','+14155550197','eXp Realty','customer','instagram',now()-interval '30 minutes',now()),
(v_account_id,'Alice','Reynolds','alice.reynolds@remax.com','+14155550198','RE/MAX','customer','referral',now()-interval '20 minutes',now()),
(v_account_id,'Albert','Fisher','albert.fisher@kwrealty.com','+14155550199','Keller Williams','customer','cold_email',now()-interval '15 minutes',now()),
(v_account_id,'Evelyn','Ellis','evelyn.ellis@compass.com','+14155550200','Compass','customer','cold_email',now()-interval '10 minutes',now()),
(v_account_id,'Billy','Harrison','billy.harrison@bhhs.com','+14155550201','Berkshire Hathaway','customer','cold_email',now()-interval '9 minutes',now()),
(v_account_id,'Dorothy','Gibson','dorothy.gibson@coldwellbanker.com','+14155550202','Coldwell Banker','customer','instagram',now()-interval '8 minutes',now()),
(v_account_id,'Russell','McDonald','russell.mcdonald@sothebys.com','+14155550203','Sotheby''s Realty','customer','referral',now()-interval '7 minutes',now()),
(v_account_id,'Frances','Cruz','frances.cruz@century21.com','+14155550204','Century 21','customer','cold_email',now()-interval '6 minutes',now()),
(v_account_id,'Wayne','Marshall','wayne.marshall@exp.com','+14155550205','eXp Realty','customer','cold_email',now()-interval '5 minutes',now()),
(v_account_id,'Theresa','Ortiz','theresa.ortiz@remax.com','+14155550206','RE/MAX','customer','cold_email',now()-interval '4 minutes',now()),
(v_account_id,'Gerald','Gomez','gerald.gomez@kwrealty.com','+14155550207','Keller Williams','customer','instagram',now()-interval '3 minutes',now()),
(v_account_id,'Sandra','Murray','sandra.murray@compass.com','+14155550208','Compass','customer','referral',now()-interval '2 minutes',now()),
(v_account_id,'Lawrence','Freeman','lawrence.freeman@bhhs.com','+14155550209','Berkshire Hathaway','customer','cold_email',now()-interval '1 minute',now()),
(v_account_id,'Melissa','Wells','melissa.wells@coldwellbanker.com','+14155550210','Coldwell Banker','customer','cold_email',now(),now()),
(v_account_id,'Willie','Webb','willie.webb@sothebys.com','+14155550211','Sotheby''s Realty','customer','cold_email',now(),now()),
(v_account_id,'Nicole','Hunter','nicole.hunter@century21.com','+14155550212','Century 21','customer','instagram',now(),now()),
(v_account_id,'Ralph','Porter','ralph.porter@exp.com','+14155550213','eXp Realty','customer','referral',now(),now()),
(v_account_id,'Frances','Simpson','frances.simpson@remax.com','+14155550214','RE/MAX','customer','cold_email',now(),now()),
(v_account_id,'Samuel','Stevens','samuel.stevens@kwrealty.com','+14155550215','Keller Williams','customer','cold_email',now(),now()),
(v_account_id,'Katherine','Tucker','katherine.tucker@compass.com','+14155550216','Compass','customer','cold_email',now(),now()),
(v_account_id,'Jamal','Washington','jamal.washington@remax.com','+14155550217','RE/MAX','customer','instagram',now(),now());

-- BATCH 2: 423 lead contacts (varied names, sources, companies)
INSERT INTO contacts (account_id, first_name, last_name, email, phone, company, status, source, created_at, updated_at)
SELECT
  v_account_id,
  first_name,
  last_name,
  lower(first_name) || '.' || lower(last_name) || seq || '@' || domain,
  '+1415555' || lpad((1000 + seq)::text, 4, '0'),
  company,
  CASE WHEN seq % 3 = 0 THEN 'customer' ELSE 'lead' END,
  (ARRAY['cold_email','cold_email','cold_email','instagram','referral'])[1 + (seq % 5)],
  now() - (seq * interval '1 day'),
  now() - (seq * interval '12 hours')
FROM (
  SELECT
    seq,
    (ARRAY['Liam','Noah','Oliver','Elijah','James','Aiden','Lucas','Mason','Ethan','Logan','Jackson','Sebastian','Jack','Owen','Theo','Caleb','Ryan','Nathan','Dylan','Henry','Wyatt','Hudson','Gabriel','Julian','Grayson','Lincoln','Eli','Connor','Landon','Isaiah','Aaron','Thomas','Luke','Hayes','Miles','Kingston','Jaxon','Jace','Kayden','Brandon','Jameson','Kyle','Blake','Colton','Brooks','Reid','Michael','Cole','Ezra','Chase','Luca','Beckett','Brayden','Bryson','Cruz','Damian','Davis','Griffin','Jordan','Jose','Ian','Parker','Zachary','Caden','Hunter','Cameron','Tucker','Easton','Cooper','Bentley','Xavier','Roman','Sawyer','Silas','Declan','Legend','Rowan','Jaxson','Emmett','Finley','Harrison','Ryder','Adriel','Kaden','Jasper','Cash','Ezekiel','Felix','Tobias','Xander','Remy','Zane','Marcus','Archer','Arthur','Max','Maxwell','Micah','Nolan','Preston','River','Rylan','Tatum','Waylon'])[1 + (seq % 100)] AS first_name,
    (ARRAY['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Martinez','Wilson','Anderson','Taylor','Thomas','Hernandez','Moore','Martin','Jackson','Thompson','White','Lopez','Lee','Gonzalez','Harris','Clark','Lewis','Robinson','Walker','Perez','Hall','Young','Allen','Sanchez','Wright','King','Scott','Green','Baker','Adams','Nelson','Hill','Ramirez','Campbell','Mitchell','Roberts','Carter','Phillips','Evans','Turner','Torres','Parker','Collins','Edwards','Stewart','Flores','Morris','Nguyen','Murphy','Rivera','Cook','Rogers','Morgan','Peterson','Cooper','Reed','Bailey','Bell','Gomez','Kelly','Howard','Ward','Cox','Diaz','Richardson','Wood','Watson','Brooks','Bennett','Gray','James','Reyes','Cruz','Hughes','Price','Myers','Long','Foster','Sanders','Ross','Morales','Powell','Sullivan','Russell','Ortiz','Jenkins','Gutierrez','Perry','Butler','Barnes','Fisher'])[1 + (seq % 100)] AS last_name,
    (ARRAY['remax.com','kwrealty.com','coldwellbanker.com','compass.com','sothebysrealty.com','bhhs.com','century21.com','exprealty.com','redfin.com','zillow.com','realtor.com','gmail.com','yahoo.com','outlook.com'])[1 + (seq % 14)] AS domain,
    (ARRAY['RE/MAX','Keller Williams','Coldwell Banker','Compass','Sotheby''s Realty','Berkshire Hathaway','Century 21','eXp Realty','Redfin','Engel & Völkers','Douglas Elliman','Howard Hanna','Long & Foster','Weichert Realtors'])[1 + (seq % 14)] AS company
  FROM generate_series(1, 423) AS seq
) AS data;

RAISE NOTICE 'Contacts inserted: 117 named + 423 generated = 540 total';
END $$;
