-- ~150 calendar activities for agency account (busy calendar look)
-- 60 past (completed) + 90 future (scheduled)
-- Run in Supabase SQL editor

DO $$
DECLARE
  v_account_id uuid := 'da99b768-79dd-48f8-af86-abf95e61a69f';
  v_user_id uuid := '54ae626a-4291-4a7e-beb4-26f7814c2491';
BEGIN

-- PAST EVENTS (60 completed, spread over last 60 days)
INSERT INTO activities (account_id, created_by, type, subject, due_date, status, created_at, updated_at)
VALUES
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Sarah Chen', now() - interval '58 days' + interval '9 hours', 'completed', now() - interval '60 days', now() - interval '58 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - James Garcia', now() - interval '57 days' + interval '10 hours', 'completed', now() - interval '59 days', now() - interval '57 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Emily Wilson', now() - interval '56 days' + interval '11 hours', 'completed', now() - interval '58 days', now() - interval '56 days'),
(v_account_id, v_user_id, 'meeting', 'Strategy Review - Nexorra Q1', now() - interval '55 days' + interval '14 hours', 'completed', now() - interval '57 days', now() - interval '55 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Robert Martinez', now() - interval '54 days' + interval '9 hours', 'completed', now() - interval '56 days', now() - interval '54 days'),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Premier Realty Group', now() - interval '53 days' + interval '10 hours', 'completed', now() - interval '55 days', now() - interval '53 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Lisa Anderson', now() - interval '52 days' + interval '11 hours', 'completed', now() - interval '54 days', now() - interval '52 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Carlos Rodriguez', now() - interval '51 days' + interval '13 hours', 'completed', now() - interval '53 days', now() - interval '51 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Jennifer Lee', now() - interval '50 days' + interval '9 hours', 'completed', now() - interval '52 days', now() - interval '50 days'),
(v_account_id, v_user_id, 'meeting', 'Campaign Review - Cold Email Batch 3', now() - interval '49 days' + interval '15 hours', 'completed', now() - interval '51 days', now() - interval '49 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - David Thompson', now() - interval '48 days' + interval '10 hours', 'completed', now() - interval '50 days', now() - interval '48 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Michelle Harris', now() - interval '47 days' + interval '11 hours', 'completed', now() - interval '49 days', now() - interval '47 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Anthony White', now() - interval '46 days' + interval '9 hours', 'completed', now() - interval '48 days', now() - interval '46 days'),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Keller Williams Flagship', now() - interval '45 days' + interval '14 hours', 'completed', now() - interval '47 days', now() - interval '45 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Kevin Clark', now() - interval '44 days' + interval '10 hours', 'completed', now() - interval '46 days', now() - interval '44 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Sandra Lewis', now() - interval '43 days' + interval '11 hours', 'completed', now() - interval '45 days', now() - interval '43 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Mark Robinson', now() - interval '42 days' + interval '9 hours', 'completed', now() - interval '44 days', now() - interval '42 days'),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() - interval '41 days' + interval '9 hours', 'completed', now() - interval '43 days', now() - interval '41 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Patricia Walker', now() - interval '40 days' + interval '10 hours', 'completed', now() - interval '42 days', now() - interval '40 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Brian Hall', now() - interval '39 days' + interval '11 hours', 'completed', now() - interval '41 days', now() - interval '39 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Karen Young', now() - interval '38 days' + interval '13 hours', 'completed', now() - interval '40 days', now() - interval '38 days'),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Coldwell Banker Elite', now() - interval '37 days' + interval '9 hours', 'completed', now() - interval '39 days', now() - interval '37 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Gary Allen', now() - interval '36 days' + interval '10 hours', 'completed', now() - interval '38 days', now() - interval '36 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Nancy King', now() - interval '35 days' + interval '11 hours', 'completed', now() - interval '37 days', now() - interval '35 days'),
(v_account_id, v_user_id, 'meeting', 'Strategy Review - Lead Gen Optimization', now() - interval '34 days' + interval '14 hours', 'completed', now() - interval '36 days', now() - interval '34 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Steven Wright', now() - interval '33 days' + interval '9 hours', 'completed', now() - interval '35 days', now() - interval '33 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Donna Scott', now() - interval '32 days' + interval '10 hours', 'completed', now() - interval '34 days', now() - interval '32 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Paul Torres', now() - interval '31 days' + interval '11 hours', 'completed', now() - interval '33 days', now() - interval '31 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Betty Nguyen', now() - interval '30 days' + interval '9 hours', 'completed', now() - interval '32 days', now() - interval '30 days'),
(v_account_id, v_user_id, 'meeting', 'Onboarding - RE/MAX Pinnacle', now() - interval '29 days' + interval '13 hours', 'completed', now() - interval '31 days', now() - interval '29 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Frank Hill', now() - interval '28 days' + interval '10 hours', 'completed', now() - interval '30 days', now() - interval '28 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ruth Green', now() - interval '27 days' + interval '11 hours', 'completed', now() - interval '29 days', now() - interval '27 days'),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() - interval '27 days' + interval '9 hours', 'completed', now() - interval '29 days', now() - interval '27 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Helen Baker', now() - interval '26 days' + interval '9 hours', 'completed', now() - interval '28 days', now() - interval '26 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Raymond Adams', now() - interval '25 days' + interval '10 hours', 'completed', now() - interval '27 days', now() - interval '25 days'),
(v_account_id, v_user_id, 'meeting', 'Campaign Review - Instagram Outreach', now() - interval '24 days' + interval '15 hours', 'completed', now() - interval '26 days', now() - interval '24 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Sharon Nelson', now() - interval '23 days' + interval '9 hours', 'completed', now() - interval '25 days', now() - interval '23 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Harold Carter', now() - interval '22 days' + interval '10 hours', 'completed', now() - interval '24 days', now() - interval '22 days'),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Sotheby''s Realty Atlanta', now() - interval '21 days' + interval '11 hours', 'completed', now() - interval '23 days', now() - interval '21 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Diane Mitchell', now() - interval '20 days' + interval '9 hours', 'completed', now() - interval '22 days', now() - interval '20 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Joe Perez', now() - interval '19 days' + interval '10 hours', 'completed', now() - interval '21 days', now() - interval '19 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Judith Roberts', now() - interval '18 days' + interval '11 hours', 'completed', now() - interval '20 days', now() - interval '18 days'),
(v_account_id, v_user_id, 'meeting', 'Strategy Review - Q1 Performance', now() - interval '17 days' + interval '14 hours', 'completed', now() - interval '19 days', now() - interval '17 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Arthur Turner', now() - interval '16 days' + interval '9 hours', 'completed', now() - interval '18 days', now() - interval '16 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Gloria Phillips', now() - interval '15 days' + interval '10 hours', 'completed', now() - interval '17 days', now() - interval '15 days'),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() - interval '14 days' + interval '9 hours', 'completed', now() - interval '16 days', now() - interval '14 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Walter Campbell', now() - interval '13 days' + interval '11 hours', 'completed', now() - interval '15 days', now() - interval '13 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Evelyn Parker', now() - interval '12 days' + interval '9 hours', 'completed', now() - interval '14 days', now() - interval '12 days'),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Berkshire Hathaway Denver', now() - interval '11 days' + interval '13 hours', 'completed', now() - interval '13 days', now() - interval '11 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Carl Evans', now() - interval '10 days' + interval '10 hours', 'completed', now() - interval '12 days', now() - interval '10 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Alice Edwards', now() - interval '9 days' + interval '11 hours', 'completed', now() - interval '11 days', now() - interval '9 days'),
(v_account_id, v_user_id, 'meeting', 'Campaign Review - Meta Ads Performance', now() - interval '8 days' + interval '15 hours', 'completed', now() - interval '10 days', now() - interval '8 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Lawrence Collins', now() - interval '7 days' + interval '9 hours', 'completed', now() - interval '9 days', now() - interval '7 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ruby Stewart', now() - interval '6 days' + interval '10 hours', 'completed', now() - interval '8 days', now() - interval '6 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ralph Morris', now() - interval '5 days' + interval '11 hours', 'completed', now() - interval '7 days', now() - interval '5 days'),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() - interval '4 days' + interval '9 hours', 'completed', now() - interval '6 days', now() - interval '4 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Wanda Rogers', now() - interval '3 days' + interval '10 hours', 'completed', now() - interval '5 days', now() - interval '3 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ernest Reed', now() - interval '2 days' + interval '11 hours', 'completed', now() - interval '4 days', now() - interval '2 days'),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Mildred Cook', now() - interval '1 day' + interval '9 hours', 'completed', now() - interval '3 days', now() - interval '1 day');

-- FUTURE EVENTS (90 scheduled, spread over next 60 days)
INSERT INTO activities (account_id, created_by, type, subject, due_date, status, created_at, updated_at)
VALUES
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Sofia Martinez', now() + interval '1 day' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Lucas Brown', now() + interval '1 day' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ava Johnson', now() + interval '1 day' + interval '14 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '2 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Liam Davis', now() + interval '2 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Mia Wilson', now() + interval '2 days' + interval '13 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Noah Garcia', now() + interval '3 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Century 21 Phoenix', now() + interval '3 days' + interval '11 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Isabella Rodriguez', now() + interval '3 days' + interval '14 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ethan Martinez', now() + interval '4 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Charlotte Anderson', now() + interval '4 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Strategy Review - Q2 Planning', now() + interval '4 days' + interval '15 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Oliver Thomas', now() + interval '5 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Amelia Jackson', now() + interval '5 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - James White', now() + interval '5 days' + interval '13 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Emma Harris', now() + interval '6 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Compass Realty Houston', now() + interval '6 days' + interval '11 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Benjamin Martin', now() + interval '6 days' + interval '14 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '7 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Henry Thompson', now() + interval '7 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ella Garcia', now() + interval '7 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Alexander Moore', now() + interval '8 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Campaign Review - Cold Email Batch 7', now() + interval '8 days' + interval '15 hours', 45, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Scarlett Taylor', now() + interval '9 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Sebastian Lee', now() + interval '9 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Aria Wilson', now() + interval '9 days' + interval '13 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Keller Williams Austin', now() + interval '10 days' + interval '10 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Jack Anderson', now() + interval '10 days' + interval '14 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Victoria Thomas', now() + interval '11 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '11 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Owen Jackson', now() + interval '11 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Grace White', now() + interval '12 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Carter Harris', now() + interval '12 days' + interval '14 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Chloe Martin', now() + interval '13 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - RE/MAX Realty Chicago', now() + interval '13 days' + interval '11 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Wyatt Thompson', now() + interval '14 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Riley Garcia', now() + interval '14 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Strategy Review - Campaign Performance', now() + interval '14 days' + interval '15 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Zoey Moore', now() + interval '15 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Nolan Taylor', now() + interval '15 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Penelope Lee', now() + interval '16 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '16 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Lincoln Wilson', now() + interval '17 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Berkshire Hathaway Seattle', now() + interval '17 days' + interval '13 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Hannah Anderson', now() + interval '18 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Grayson Thomas', now() + interval '18 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Layla Jackson', now() + interval '19 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Campaign Review - Instagram DMs', now() + interval '19 days' + interval '15 hours', 45, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Julian White', now() + interval '20 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Natalie Harris', now() + interval '20 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Eli Martin', now() + interval '21 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '21 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Aurora Thompson', now() + interval '22 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Coldwell Banker Miami', now() + interval '22 days' + interval '11 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Levi Garcia', now() + interval '23 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Savannah Moore', now() + interval '23 days' + interval '14 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Dominic Taylor', now() + interval '24 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Strategy Review - Onboarding Funnel', now() + interval '24 days' + interval '15 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Claire Lee', now() + interval '25 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Miles Wilson', now() + interval '25 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Stella Anderson', now() + interval '26 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '26 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Roman Thomas', now() + interval '27 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Sotheby''s Realty Dallas', now() + interval '27 days' + interval '13 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Luna Jackson', now() + interval '28 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Knox White', now() + interval '28 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ivy Harris', now() + interval '29 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Campaign Review - Q2 Leads', now() + interval '29 days' + interval '15 hours', 45, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ezra Martin', now() + interval '30 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Violet Thompson', now() + interval '30 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Zion Garcia', now() + interval '31 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '31 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Exp Realty Portland', now() + interval '32 days' + interval '11 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ember Moore', now() + interval '33 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Atlas Taylor', now() + interval '33 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Nova Lee', now() + interval '34 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Strategy Review - Revenue Targets', now() + interval '35 days' + interval '14 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Kai Wilson', now() + interval '36 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Juno Anderson', now() + interval '36 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '37 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Keller Williams Nashville', now() + interval '38 days' + interval '10 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Orion Thomas', now() + interval '39 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Celeste Jackson', now() + interval '40 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Campaign Review - Cold Email Batch 9', now() + interval '41 days' + interval '15 hours', 45, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Phoenix White', now() + interval '42 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - River Harris', now() + interval '43 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Indigo Martin', now() + interval '44 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '44 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Cedar Thompson', now() + interval '45 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - Compass Realty Denver', now() + interval '46 days' + interval '11 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Sage Garcia', now() + interval '47 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Wren Moore', now() + interval '48 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Lark Taylor', now() + interval '49 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Strategy Review - H2 Planning', now() + interval '50 days' + interval '14 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Storm Lee', now() + interval '51 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Reef Wilson', now() + interval '52 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Weekly Team Standup', now() + interval '52 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Briar Anderson', now() + interval '53 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Onboarding - RE/MAX Realty Boston', now() + interval '54 days' + interval '10 hours', 60, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Grove Thomas', now() + interval '55 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Fern Jackson', now() + interval '56 days' + interval '11 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Campaign Review - Full Funnel Q2', now() + interval '57 days' + interval '15 hours', 45, 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Ash White', now() + interval '58 days' + interval '9 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Bay Harris', now() + interval '59 days' + interval '10 hours', 'scheduled', now(), now()),
(v_account_id, v_user_id, 'meeting', 'Discovery Call - Vale Martin', now() + interval '60 days' + interval '11 hours', 'scheduled', now(), now());

RAISE NOTICE 'Calendar events inserted: 60 past + 90 future = 150 total';
END $$;
