-- Insert 117 display-only sub-accounts under the Nexorra agency
-- These appear in the account switcher dropdown but have no users or data
-- Run in Supabase SQL editor

DO $$
DECLARE
  agency_id UUID := 'da99b768-79dd-48f8-af86-abf95e61a69f';
BEGIN

INSERT INTO accounts (id, name, slug, parent_account_id, created_at, updated_at) VALUES
-- Solo agents (US & Canada)
(gen_random_uuid(), 'Jordan Whitfield', 'jordan-whitfield', agency_id, NOW() - INTERVAL '18 months', NOW()),
(gen_random_uuid(), 'Megan Calloway', 'megan-calloway', agency_id, NOW() - INTERVAL '17 months', NOW()),
(gen_random_uuid(), 'Tyler Benson', 'tyler-benson', agency_id, NOW() - INTERVAL '16 months', NOW()),
(gen_random_uuid(), 'Ashley Monroe', 'ashley-monroe', agency_id, NOW() - INTERVAL '16 months', NOW()),
(gen_random_uuid(), 'Derek Hawkins', 'derek-hawkins', agency_id, NOW() - INTERVAL '15 months', NOW()),
(gen_random_uuid(), 'Caitlin Forde', 'caitlin-forde', agency_id, NOW() - INTERVAL '15 months', NOW()),
(gen_random_uuid(), 'Marcus Webb', 'marcus-webb', agency_id, NOW() - INTERVAL '14 months', NOW()),
(gen_random_uuid(), 'Natalie Stern', 'natalie-stern', agency_id, NOW() - INTERVAL '14 months', NOW()),
(gen_random_uuid(), 'Brendan Kowalski', 'brendan-kowalski', agency_id, NOW() - INTERVAL '13 months', NOW()),
(gen_random_uuid(), 'Samantha Reeves', 'samantha-reeves', agency_id, NOW() - INTERVAL '13 months', NOW()),
(gen_random_uuid(), 'Ryan Castellano', 'ryan-castellano', agency_id, NOW() - INTERVAL '12 months', NOW()),
(gen_random_uuid(), 'Lauren Thibodeau', 'lauren-thibodeau', agency_id, NOW() - INTERVAL '12 months', NOW()),
(gen_random_uuid(), 'Ethan Morales', 'ethan-morales', agency_id, NOW() - INTERVAL '11 months', NOW()),
(gen_random_uuid(), 'Chelsea Drummond', 'chelsea-drummond', agency_id, NOW() - INTERVAL '11 months', NOW()),
(gen_random_uuid(), 'Kevin Abernathy', 'kevin-abernathy', agency_id, NOW() - INTERVAL '10 months', NOW()),
(gen_random_uuid(), 'Danielle Pratt', 'danielle-pratt', agency_id, NOW() - INTERVAL '10 months', NOW()),
(gen_random_uuid(), 'Patrick Nguyen', 'patrick-nguyen', agency_id, NOW() - INTERVAL '9 months', NOW()),
(gen_random_uuid(), 'Rachel Goldstein', 'rachel-goldstein', agency_id, NOW() - INTERVAL '9 months', NOW()),
(gen_random_uuid(), 'Scott Dempsey', 'scott-dempsey', agency_id, NOW() - INTERVAL '9 months', NOW()),
(gen_random_uuid(), 'Brittany Okonkwo', 'brittany-okonkwo', agency_id, NOW() - INTERVAL '8 months', NOW()),
(gen_random_uuid(), 'Nathan Pearce', 'nathan-pearce', agency_id, NOW() - INTERVAL '8 months', NOW()),
(gen_random_uuid(), 'Tiffany Vasquez', 'tiffany-vasquez', agency_id, NOW() - INTERVAL '8 months', NOW()),
(gen_random_uuid(), 'Connor Fitzpatrick', 'connor-fitzpatrick', agency_id, NOW() - INTERVAL '7 months', NOW()),
(gen_random_uuid(), 'Melissa Hartley', 'melissa-hartley', agency_id, NOW() - INTERVAL '7 months', NOW()),
(gen_random_uuid(), 'Aaron Sandoval', 'aaron-sandoval', agency_id, NOW() - INTERVAL '7 months', NOW()),
(gen_random_uuid(), 'Jennifer Bouchard', 'jennifer-bouchard', agency_id, NOW() - INTERVAL '7 months', NOW()),
(gen_random_uuid(), 'Brandon Kimura', 'brandon-kimura', agency_id, NOW() - INTERVAL '6 months', NOW()),
(gen_random_uuid(), 'Stephanie Leclaire', 'stephanie-leclaire', agency_id, NOW() - INTERVAL '6 months', NOW()),
(gen_random_uuid(), 'Colin Merritt', 'colin-merritt', agency_id, NOW() - INTERVAL '6 months', NOW()),
(gen_random_uuid(), 'Amanda Sherwood', 'amanda-sherwood', agency_id, NOW() - INTERVAL '6 months', NOW()),
(gen_random_uuid(), 'Travis Hollingsworth', 'travis-hollingsworth', agency_id, NOW() - INTERVAL '5 months', NOW()),
(gen_random_uuid(), 'Kimberly Rousseau', 'kimberly-rousseau', agency_id, NOW() - INTERVAL '5 months', NOW()),
(gen_random_uuid(), 'Dustin Carver', 'dustin-carver', agency_id, NOW() - INTERVAL '5 months', NOW()),
(gen_random_uuid(), 'Heather Nakamura', 'heather-nakamura', agency_id, NOW() - INTERVAL '5 months', NOW()),
(gen_random_uuid(), 'Jared Billingsley', 'jared-billingsley', agency_id, NOW() - INTERVAL '5 months', NOW()),
(gen_random_uuid(), 'Monica Delacroix', 'monica-delacroix', agency_id, NOW() - INTERVAL '4 months', NOW()),
(gen_random_uuid(), 'Shane Covington', 'shane-covington', agency_id, NOW() - INTERVAL '4 months', NOW()),
(gen_random_uuid(), 'Vanessa Chung', 'vanessa-chung', agency_id, NOW() - INTERVAL '4 months', NOW()),
(gen_random_uuid(), 'Hunter Blackwell', 'hunter-blackwell', agency_id, NOW() - INTERVAL '4 months', NOW()),
(gen_random_uuid(), 'Courtney Bergeron', 'courtney-bergeron', agency_id, NOW() - INTERVAL '4 months', NOW()),
(gen_random_uuid(), 'Dale Worthington', 'dale-worthington', agency_id, NOW() - INTERVAL '4 months', NOW()),
(gen_random_uuid(), 'Lindsay Fontaine', 'lindsay-fontaine', agency_id, NOW() - INTERVAL '3 months', NOW()),
(gen_random_uuid(), 'Wesley Harrington', 'wesley-harrington', agency_id, NOW() - INTERVAL '3 months', NOW()),
(gen_random_uuid(), 'Cassandra Leclerc', 'cassandra-leclerc', agency_id, NOW() - INTERVAL '3 months', NOW()),
(gen_random_uuid(), 'Joel Templeton', 'joel-templeton', agency_id, NOW() - INTERVAL '3 months', NOW()),
(gen_random_uuid(), 'Amy Witherspoon', 'amy-witherspoon', agency_id, NOW() - INTERVAL '3 months', NOW()),
(gen_random_uuid(), 'Caleb Drummond', 'caleb-drummond', agency_id, NOW() - INTERVAL '3 months', NOW()),
(gen_random_uuid(), 'Paige McAllister', 'paige-mcallister', agency_id, NOW() - INTERVAL '3 months', NOW()),
(gen_random_uuid(), 'Garrett Sullivan', 'garrett-sullivan', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Allison Fairchild', 'allison-fairchild', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Nolan Prescott', 'nolan-prescott', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Tabitha Chambers', 'tabitha-chambers', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Reid Gallagher', 'reid-gallagher', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Jacqueline Odom', 'jacqueline-odom', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Devin Castellanos', 'devin-castellanos', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Sarah Beth Coulter', 'sarah-beth-coulter', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Logan Pendergast', 'logan-pendergast', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Autumn Wentworth', 'autumn-wentworth', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Cameron Holloway', 'cameron-holloway', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Nicole Beaumont', 'nicole-beaumont', agency_id, NOW() - INTERVAL '2 months', NOW()),
(gen_random_uuid(), 'Grant Ashford', 'grant-ashford', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Sabrina Delisle', 'sabrina-delisle', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Spencer Whitmore', 'spencer-whitmore', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Fiona Macgregor', 'fiona-macgregor', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Austin Langford', 'austin-langford', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Kristen Ballard', 'kristen-ballard', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Zach Carmichael', 'zach-carmichael', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Marissa Trevino', 'marissa-trevino', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Colton Whitaker', 'colton-whitaker', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Priya Mehta', 'priya-mehta', agency_id, NOW() - INTERVAL '1 month', NOW()),
(gen_random_uuid(), 'Blake Sorensen', 'blake-sorensen', agency_id, NOW() - INTERVAL '3 weeks', NOW()),
(gen_random_uuid(), 'Hannah Lefebvre', 'hannah-lefebvre', agency_id, NOW() - INTERVAL '3 weeks', NOW()),
(gen_random_uuid(), 'Zachary Pemberton', 'zachary-pemberton', agency_id, NOW() - INTERVAL '3 weeks', NOW()),
(gen_random_uuid(), 'Candace Thurston', 'candace-thurston', agency_id, NOW() - INTERVAL '3 weeks', NOW()),
(gen_random_uuid(), 'Mason Aldridge', 'mason-aldridge', agency_id, NOW() - INTERVAL '3 weeks', NOW()),
(gen_random_uuid(), 'Leah Vanburen', 'leah-vanburen', agency_id, NOW() - INTERVAL '3 weeks', NOW()),
(gen_random_uuid(), 'Eli Strickland', 'eli-strickland', agency_id, NOW() - INTERVAL '3 weeks', NOW()),
(gen_random_uuid(), 'Bridget Mahoney', 'bridget-mahoney', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Owen Bancroft', 'owen-bancroft', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Trinity Larsson', 'trinity-larsson', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Bryce Davenport', 'bryce-davenport', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Shelby Garrison', 'shelby-garrison', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Landon Rutherford', 'landon-rutherford', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Isabel Tremblay', 'isabel-tremblay', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Luke Stratton', 'luke-stratton', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Amber Lockwood', 'amber-lockwood', agency_id, NOW() - INTERVAL '2 weeks', NOW()),
(gen_random_uuid(), 'Jaxon Fielding', 'jaxon-fielding', agency_id, NOW() - INTERVAL '10 days', NOW()),
(gen_random_uuid(), 'Elise Champagne', 'elise-champagne', agency_id, NOW() - INTERVAL '10 days', NOW()),
(gen_random_uuid(), 'Carter Holman', 'carter-holman', agency_id, NOW() - INTERVAL '10 days', NOW()),
(gen_random_uuid(), 'Molly Steinberg', 'molly-steinberg', agency_id, NOW() - INTERVAL '10 days', NOW()),
(gen_random_uuid(), 'Parker Redmond', 'parker-redmond', agency_id, NOW() - INTERVAL '9 days', NOW()),
(gen_random_uuid(), 'Nadia Fontaine', 'nadia-fontaine', agency_id, NOW() - INTERVAL '9 days', NOW()),
(gen_random_uuid(), 'Griffin O''Brien', 'griffin-obrien', agency_id, NOW() - INTERVAL '9 days', NOW()),
(gen_random_uuid(), 'Brianna Kovacs', 'brianna-kovacs', agency_id, NOW() - INTERVAL '8 days', NOW()),
(gen_random_uuid(), 'Sawyer Langston', 'sawyer-langston', agency_id, NOW() - INTERVAL '8 days', NOW()),
(gen_random_uuid(), 'Veronica Ouellet', 'veronica-ouellet', agency_id, NOW() - INTERVAL '7 days', NOW()),
(gen_random_uuid(), 'Wyatt Pemberton', 'wyatt-pemberton', agency_id, NOW() - INTERVAL '7 days', NOW()),
(gen_random_uuid(), 'Jade Villeneuve', 'jade-villeneuve', agency_id, NOW() - INTERVAL '6 days', NOW()),
(gen_random_uuid(), 'Finn Caldwell', 'finn-caldwell', agency_id, NOW() - INTERVAL '6 days', NOW()),
(gen_random_uuid(), 'Alexis Boudreau', 'alexis-boudreau', agency_id, NOW() - INTERVAL '5 days', NOW()),
(gen_random_uuid(), 'Ryder Callahan', 'ryder-callahan', agency_id, NOW() - INTERVAL '5 days', NOW()),
(gen_random_uuid(), 'Celeste Bergeron', 'celeste-bergeron', agency_id, NOW() - INTERVAL '4 days', NOW()),
(gen_random_uuid(), 'Jonah Whiteside', 'jonah-whiteside', agency_id, NOW() - INTERVAL '4 days', NOW()),
(gen_random_uuid(), 'Tara Mcintosh', 'tara-mcintosh', agency_id, NOW() - INTERVAL '4 days', NOW()),
(gen_random_uuid(), 'Dominic Arsenault', 'dominic-arsenault', agency_id, NOW() - INTERVAL '3 days', NOW()),
(gen_random_uuid(), 'Payton Ashworth', 'payton-ashworth', agency_id, NOW() - INTERVAL '3 days', NOW()),
(gen_random_uuid(), 'Rose Dion', 'rose-dion', agency_id, NOW() - INTERVAL '3 days', NOW()),
(gen_random_uuid(), 'Miles Fairbanks', 'miles-fairbanks', agency_id, NOW() - INTERVAL '2 days', NOW()),
(gen_random_uuid(), 'Gemma Lapointe', 'gemma-lapointe', agency_id, NOW() - INTERVAL '2 days', NOW()),
(gen_random_uuid(), 'Brady Whitfield', 'brady-whitfield', agency_id, NOW() - INTERVAL '2 days', NOW()),
-- Team accounts (outliers with 10-12 deals/month)
(gen_random_uuid(), 'Harrison Homes Group', 'harrison-homes-group', agency_id, NOW() - INTERVAL '20 months', NOW()),
(gen_random_uuid(), 'Pacific West Realty Team', 'pacific-west-realty-team', agency_id, NOW() - INTERVAL '19 months', NOW()),
(gen_random_uuid(), 'Maple & Co Real Estate', 'maple-co-real-estate', agency_id, NOW() - INTERVAL '17 months', NOW());

END $$;
