#!/usr/bin/env node

/**
 * Video Compositor
 * Combines profile screenshots, CRM demo, and talking head overlay
 * into a final ~14.2s personalized video using ffmpeg.
 *
 * Timing:
 *   Profile screenshots: 17s (13s static + 3s scroll flick at 13s mark + 1s hold at top)
 *   CRM recording: fills the REST of the talking head duration (~130s)
 *   Talking head: circular 160px overlay in bottom-left, FULL LENGTH (~145.5s)
 *   Final: speed up 1.3x → ~99s
 *
 * Usage: npx tsx scripts/loom-video/composite.ts <screenshots_dir> [talking_head] [crm_demo] [output_path]
 */

import { execSync, exec } from "child_process";
import { promisify } from "util";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const execAsync = promisify(exec);

const PROJECT_ROOT = path.resolve(__dirname, "../..");
const DEFAULT_TALKING_HEAD = path.join(PROJECT_ROOT, "assets/video/talking-head.mp4");
const DEFAULT_CRM_DEMO = path.join(PROJECT_ROOT, "assets/video/crm-demo.mp4");
const PRERENDERED_TAIL = path.join(PROJECT_ROOT, "assets/video/crm-tail-prerendered.mp4");
// Pre-rendered circular TH overlay (VP9 + alpha) — generated by prerender-th-circle.ts
const TH_CIRCLE_SPED = path.join(PROJECT_ROOT, "assets/video/th-circle-sped.webm");
// Static 200x200 circle mask for alphamerge (faster than per-frame geq)
const CIRCLE_MASK = path.join(PROJECT_ROOT, "assets/video/circle-mask-200.png");
// Pre-rendered 200x200 talking head (cropped, flipped, sped up) — no 1080p decode per lead
const TH_200_SPED = path.join(PROJECT_ROOT, "assets/video/th-200-sped.mp4");

export interface CompositeOptions {
  screenshotsDir: string;
  talkingHeadPath: string;
  crmRecordingPath: string;
  outputPath: string;
}

function checkFfmpeg(): void {
  try {
    execSync("which ffmpeg", { stdio: "pipe" });
  } catch {
    throw new Error(
      "ffmpeg not found. Install it with: sudo apt install ffmpeg"
    );
  }
}

function validateInputs(opts: CompositeOptions): void {
  if (!fs.existsSync(opts.screenshotsDir)) {
    throw new Error(`Screenshots directory not found: ${opts.screenshotsDir}`);
  }
  if (!fs.existsSync(opts.talkingHeadPath)) {
    throw new Error(`Talking head video not found: ${opts.talkingHeadPath}`);
  }
  if (!fs.existsSync(opts.crmRecordingPath)) {
    throw new Error(`CRM recording not found: ${opts.crmRecordingPath}`);
  }

  const frames = fs
    .readdirSync(opts.screenshotsDir)
    .filter((f) => f.endsWith(".png"));
  if (frames.length === 0) {
    throw new Error(`No PNG frames found in ${opts.screenshotsDir}`);
  }
}

function ffmpeg(args: string, timeoutMs = 60000): void {
  execSync(`ffmpeg -y ${args}`, { stdio: "pipe", timeout: timeoutMs });
}

async function ffmpegAsync(args: string, timeoutMs = 60000): Promise<void> {
  await execAsync(`ffmpeg -y ${args}`, { timeout: timeoutMs, maxBuffer: 10 * 1024 * 1024 });
}

/**
 * SUPER FAST PATH: alphamerge circle mask + pre-rendered tail.
 * Fully async — does NOT block the Node.js event loop, so all workers run in parallel.
 */
async function compositeSuperFast(opts: CompositeOptions, staticFrame: string): Promise<string> {
  const thDuration = 17 / 1.3; // 13.077s — profile portion sped up 1.3x

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "loom-super-"));
  const profileSped = path.join(tmpDir, "profile_sped.mp4");
  const concatList = path.join(tmpDir, "concat.txt");

  try {
    // Priority: use pre-rendered 200x200 TH (fastest) → alphamerge fullsize → geq fallback
    const usePrerendered = fs.existsSync(TH_200_SPED) && fs.existsSync(CIRCLE_MASK);
    const useAlphamerge = !usePrerendered && fs.existsSync(CIRCLE_MASK);
    const method = usePrerendered ? "th-200-sped+alphamerge" : useAlphamerge ? "alphamerge" : "geq";
    console.log(`[composite] SUPER FAST — ${method} circle + static bg...`);

    // CRITICAL: looped images default to 25fps but prerendered tail is 30fps /
    // time_base=1/15360. Mismatched fps+timescale → freeze at concat seam.
    // Fix: fps=30 filter on bg + -video_track_timescale 15360 on output.
    let filterComplex: string;
    let ffmpegInputs: string;

    if (usePrerendered) {
      // Fastest path: 3 inputs — [0] static bg, [1] pre-rendered 200x200 TH, [2] circle mask
      // No 1080p decode, no crop/scale/speedup transforms — all pre-computed once.
      filterComplex = [
        "[0:v]scale=1920:1080,fps=30[bg];",
        "[1:v][2:v]alphamerge[head];",
        "[bg][head]overlay=20:H-h-20[v]",
      ].join("");
      ffmpegInputs =
        `-loop 1 -t ${thDuration.toFixed(3)} -i "${staticFrame}" ` +
        `-i "${TH_200_SPED}" ` +
        `-loop 1 -t ${thDuration.toFixed(3)} -i "${CIRCLE_MASK}" `;
    } else if (useAlphamerge) {
      // alphamerge path: 3 inputs — [0] static bg, [1] talking head, [2] circle mask
      filterComplex = [
        "[0:v]scale=1920:1080,fps=30[bg];",
        "[1:v]trim=0:17,setpts=PTS-STARTPTS,setpts=PTS/1.3,",
        "crop=720:720:280:0,hflip,scale=200:200[th];",
        "[th][2:v]alphamerge[head];",
        "[bg][head]overlay=20:H-h-20[v];",
        "[1:a]atrim=start=0:end=17,asetpts=PTS-STARTPTS,atempo=1.3[a]",
      ].join("");
      ffmpegInputs =
        `-loop 1 -t ${thDuration.toFixed(3)} -i "${staticFrame}" ` +
        `-i "${opts.talkingHeadPath}" ` +
        `-loop 1 -t ${thDuration.toFixed(3)} -i "${CIRCLE_MASK}" `;
    } else {
      // geq fallback: 2 inputs — [0] static bg, [1] talking head
      filterComplex = [
        "[0:v]scale=1920:1080,fps=30[bg];",
        "[1:v]trim=0:17,setpts=PTS-STARTPTS,setpts=PTS/1.3,",
        "crop=720:720:280:0,hflip,scale=200:200,format=yuva420p,",
        "geq=lum='p(X,Y)':a='if(gt(pow(X-100,2)+pow(Y-100,2),pow(100,2)),0,255)'[head];",
        "[bg][head]overlay=20:H-h-20[v];",
        "[1:a]atrim=start=0:end=17,asetpts=PTS-STARTPTS,atempo=1.3[a]",
      ].join("");
      ffmpegInputs =
        `-loop 1 -t ${thDuration.toFixed(3)} -i "${staticFrame}" ` +
        `-i "${opts.talkingHeadPath}" `;
    }

    // Audio source: pre-rendered TH has audio already processed (input 1);
    // alphamerge/geq paths process audio inline via [a] filtergraph label.
    const audioMap = usePrerendered ? `-map 1:a` : `-map "[a]"`;
    await ffmpegAsync(
      `${ffmpegInputs}` +
      `-filter_complex "${filterComplex}" ` +
      `-map "[v]" ${audioMap} -t ${thDuration.toFixed(3)} ` +
      `-c:v libx264 -preset ultrafast -crf 23 -pix_fmt yuv420p ` +
      `-video_track_timescale 15360 ` +   // match tail's timescale
      `-force_key_frames "0,${(thDuration - 0.1).toFixed(2)}" ` +  // keyframe at seam → no freeze
      `-c:a aac -b:a 128k "${profileSped}"`,
      60000
    );

    console.log("[composite] Concatenating with pre-rendered tail...");
    fs.writeFileSync(concatList, `file '${profileSped}'\nfile '${PRERENDERED_TAIL}'\n`);
    // -c copy keeps original file size. Freeze-free because profileSped ends on a keyframe
    // (forced via -force_key_frames in the encoding step above).
    await ffmpegAsync(`-f concat -safe 0 -i "${concatList}" -c copy "${opts.outputPath}"`, 30000);

    const stats = fs.statSync(opts.outputPath);
    console.log(`[composite] Done. ${opts.outputPath} (${(stats.size / 1024 / 1024).toFixed(1)}MB)`);
    return opts.outputPath;
  } finally {
    if (fs.existsSync(tmpDir)) fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

export async function composite(opts: CompositeOptions): Promise<string> {
  checkFfmpeg();
  validateInputs(opts);

  const frames = fs.readdirSync(opts.screenshotsDir).filter(f => f.endsWith(".png")).sort();
  const staticFrame = path.join(opts.screenshotsDir, frames[0]);

  // SUPER FAST PATH: pre-rendered tail + geq circle mask (2 ffmpeg calls, ~7s)
  if (fs.existsSync(PRERENDERED_TAIL)) {
    return compositeSuperFast(opts, staticFrame);
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "loom-composite-"));
  const profileVideo = path.join(tmpDir, "profile.mp4");
  const concatList = path.join(tmpDir, "concat.txt");
  const baseVideo = path.join(tmpDir, "base.mp4");
  const overlayVideo = path.join(tmpDir, "overlay.mp4");

  // Ensure output directory exists
  const outputDir = path.dirname(opts.outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  try {
    const scrollFrames = frames.slice(1);
    const staticVideo = path.join(tmpDir, "static.mp4");
    const scrollVideo = path.join(tmpDir, "scroll.mp4");

    // ---------------------------------------------------------------
    // Step 1: Convert static first frame to 13s video at 30fps
    // ---------------------------------------------------------------
    console.log("[composite] Creating 13s static portion...");
    ffmpeg(
      `-loop 1 -i "${staticFrame}" -c:v libx264 -t 13 ` +
        `-pix_fmt yuv420p -vf "scale=1920:1080" -preset ultrafast -crf 23 -r 30 "${staticVideo}"`
    );

    // ---------------------------------------------------------------
    // Step 2: Convert scroll frames to 3s video
    //   Scroll animation: ~1.5s scroll down ~550px, 0.5s hold, ~1s scroll back up
    //   Total: 3s — fps calculated from frame count
    // ---------------------------------------------------------------
    const holdVideo = path.join(tmpDir, "hold.mp4");

    if (scrollFrames.length > 0) {
      // Target 3s for scroll animation. More frames = higher fps for same duration.
      const scrollDuration = 3.0;
      const scrollFps = Math.max(5, Math.round(scrollFrames.length / scrollDuration));
      console.log(
        `[composite] Creating ${scrollDuration}s scroll portion (${scrollFrames.length} frames @ ${scrollFps}fps)...`
      );
      ffmpeg(
        `-framerate ${scrollFps} -start_number 1 -i "${opts.screenshotsDir}/frame_%05d.png" ` +
          `-c:v libx264 -pix_fmt yuv420p -vf "scale=1920:1080" -preset ultrafast -crf 23 "${scrollVideo}"`
      );

      // Step 2c: Generate 1s hold at top (loop first frame)
      console.log("[composite] Creating 1s hold at top...");
      ffmpeg(
        `-loop 1 -i "${staticFrame}" -c:v libx264 -t 1 ` +
          `-pix_fmt yuv420p -vf "scale=1920:1080" -preset ultrafast -crf 23 -r 30 "${holdVideo}"`
      );

      // Concatenate static (13s) + scroll (3s) + hold (1s) = 17s profile video
      const profileConcat = path.join(tmpDir, "profile_concat.txt");
      fs.writeFileSync(
        profileConcat,
        `file '${staticVideo}'\nfile '${scrollVideo}'\nfile '${holdVideo}'\n`
      );
      ffmpeg(
        `-f concat -safe 0 -i "${profileConcat}" -c copy "${profileVideo}"`
      );
    } else {
      // No scroll frames — extend static to 17s
      console.log("[composite] No scroll frames, extending static to 17s...");
      ffmpeg(
        `-loop 1 -i "${staticFrame}" -c:v libx264 -t 17 ` +
          `-pix_fmt yuv420p -vf "scale=1920:1080" -preset ultrafast -crf 23 -r 30 "${profileVideo}"`
      );
    }

    // NOTE: Browser chrome frame is now composited per-frame in capture-profile.ts
    // (each screenshot already includes the Chrome header at 1920x1080)

    const profileDuration = 17; // 13s static + 3s scroll flick + 1s hold

    // ---------------------------------------------------------------
    // FAST PATH: pre-rendered CRM tail exists → only process 17s profile clip.
    //   ~8x faster: overlay TH on 17s profile → speed up → concat with tail (copy).
    //   Generate the tail once with: npx tsx scripts/loom-video/prerender-tail.ts
    // ---------------------------------------------------------------
    if (fs.existsSync(PRERENDERED_TAIL)) {
      console.log("[composite] FAST PATH — pre-rendered tail found. Processing 17s profile only...");

      const filterComplex = [
        "[1:v]crop=720:720:280:0,hflip,scale=200:200,format=yuva420p,",
        "geq=lum='p(X,Y)':a='if(gt(pow(X-100,2)+pow(Y-100,2),pow(100,2)),0,255)'",
        "[head];",
        "[0:v][head]overlay=20:H-h-20[v]",
      ].join("");

      const profileWithHead = path.join(tmpDir, "profile_with_head.mp4");
      console.log("[composite] Overlaying talking head on 17s profile...");
      ffmpeg(
        `-i "${profileVideo}" -t ${profileDuration} -i "${opts.talkingHeadPath}" ` +
          `-filter_complex "${filterComplex}" ` +
          `-map "[v]" -map 1:a -t ${profileDuration} ` +
          `-c:v libx264 -preset ultrafast -crf 23 -pix_fmt yuv420p ` +
          `-c:a aac -b:a 128k "${profileWithHead}"`,
        120000
      );

      const profileSped = path.join(tmpDir, "profile_sped.mp4");
      const profileSpedDuration = (profileDuration / 1.3).toFixed(1);
      console.log(`[composite] Speeding up 1.3x → ~${profileSpedDuration}s...`);
      ffmpeg(
        `-i "${profileWithHead}" ` +
          `-filter_complex "[0:v]setpts=PTS/1.3[v];[0:a]atempo=1.3[a]" ` +
          `-map "[v]" -map "[a]" ` +
          `-c:v libx264 -preset ultrafast -crf 23 -pix_fmt yuv420p ` +
          `-c:a aac -b:a 128k "${profileSped}"`,
        120000
      );

      console.log("[composite] Concatenating with pre-rendered tail (stream copy)...");
      fs.writeFileSync(concatList, `file '${profileSped}'\nfile '${PRERENDERED_TAIL}'\n`);
      ffmpeg(`-f concat -safe 0 -i "${concatList}" -c copy "${opts.outputPath}"`, 60000);

    } else {
      // ---------------------------------------------------------------
      // SLOW PATH: no pre-rendered tail — process the full video.
      //   Run `npx tsx scripts/loom-video/prerender-tail.ts` once to enable fast path.
      // ---------------------------------------------------------------
      console.log("[composite] SLOW PATH — run prerender-tail.ts to enable fast path.");

      const talkingHeadDuration = parseFloat(
        execSync(`ffprobe -v quiet -show_format "${opts.talkingHeadPath}" | grep duration | cut -d= -f2`, { encoding: 'utf-8' }).trim()
      );
      const crmDuration = Math.max(1, talkingHeadDuration - profileDuration);
      console.log(`[composite] Talking head: ${talkingHeadDuration.toFixed(1)}s, Profile: ${profileDuration}s, CRM fill: ${crmDuration.toFixed(1)}s`);

      const crmNormalized = path.join(tmpDir, "crm_normalized.mp4");
      console.log(`[composite] Extracting ${crmDuration.toFixed(1)}s of CRM demo...`);
      ffmpeg(
        `-stream_loop -1 -i "${opts.crmRecordingPath}" -t ${crmDuration} -c:v libx264 ` +
          `-pix_fmt yuv420p -vf "scale=1920:1080" -preset ultrafast -crf 23 -r 30 "${crmNormalized}"`,
        300000
      );

      console.log(`[composite] Concatenating profile + CRM → ${talkingHeadDuration.toFixed(1)}s base...`);
      fs.writeFileSync(concatList, `file '${profileVideo}'\nfile '${crmNormalized}'\n`);
      ffmpeg(`-f concat -safe 0 -i "${concatList}" -c copy "${baseVideo}"`, 300000);

      console.log("[composite] Overlaying circular talking head...");
      const baseDuration = parseFloat(
        execSync(`ffprobe -v quiet -show_format "${baseVideo}" | grep duration | cut -d= -f2`, { encoding: 'utf-8' }).trim()
      );

      const filterComplex = [
        "[1:v]crop=720:720:280:0,hflip,scale=200:200,format=yuva420p,",
        "geq=lum='p(X,Y)':a='if(gt(pow(X-100,2)+pow(Y-100,2),pow(100,2)),0,255)'",
        "[head];",
        "[0:v][head]overlay=20:H-h-20[v]",
      ].join("");

      ffmpeg(
        `-i "${baseVideo}" -i "${opts.talkingHeadPath}" ` +
          `-filter_complex "${filterComplex}" ` +
          `-map "[v]" -map 1:a -t ${baseDuration} ` +
          `-c:v libx264 -preset ultrafast -crf 23 -pix_fmt yuv420p ` +
          `-c:a aac -b:a 128k "${overlayVideo}"`,
        600000
      );

      const finalDuration = (talkingHeadDuration / 1.3).toFixed(1);
      console.log(`[composite] Speeding up 1.3x → ~${finalDuration}s final (HD)...`);
      ffmpeg(
        `-i "${overlayVideo}" ` +
          `-filter_complex "[0:v]setpts=PTS/1.3[v];[0:a]atempo=1.3[a]" ` +
          `-map "[v]" -map "[a]" ` +
          `-c:v libx264 -preset ultrafast -crf 23 -pix_fmt yuv420p ` +
          `-c:a aac -b:a 128k ` +
          `-movflags +faststart "${opts.outputPath}"`,
        600000
      );
    }

    const stats = fs.statSync(opts.outputPath);
    console.log(
      `[composite] Done. Output: ${opts.outputPath} (${(stats.size / 1024 / 1024).toFixed(1)}MB)`
    );
    return opts.outputPath;
  } finally {
    // Clean up temp files
    if (fs.existsSync(tmpDir)) {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  }
}

// CLI entry point
if (require.main === module) {
  const args = process.argv.slice(2);
  const screenshotsDir = args[0];
  const talkingHeadPath = args[1] || DEFAULT_TALKING_HEAD;
  const crmRecordingPath = args[2] || DEFAULT_CRM_DEMO;
  const outputPath = args[3] || path.join(screenshotsDir || ".", "output.mp4");

  if (!screenshotsDir) {
    console.error(
      "Usage: npx tsx scripts/loom-video/composite.ts <screenshots_dir> [talking_head] [crm_demo] [output_path]"
    );
    process.exit(1);
  }

  try {
    composite({ screenshotsDir, talkingHeadPath, crmRecordingPath, outputPath });
  } catch (err) {
    console.error(
      "[composite] FATAL:",
      err instanceof Error ? err.message : String(err)
    );
    process.exit(1);
  }
}
